fix:  TypeError: (0 , multer_1.default) is not a function was occurring because the multer package was being imported as a default import but needed to be imported as a namespace import